#!/usr/bin/env python3
"""Copy the two upstream libraries, or verify the checked-in snapshot offline."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
LIBRARIES = {"CapsomniaControl": "cpsm", "MacStateCore": "MacReady"}


def files_and_hashes(directory):
    return {
        str(path.relative_to(directory)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(directory.rglob("*"))
        if path.is_file() and path.name != "snapshot.json" and ".build" not in path.parts
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify snapshots without sibling repositories")
    parser.add_argument("--cpsm", type=Path, default=ROOT.parent / "cpsm")
    parser.add_argument("--macready", type=Path, default=ROOT.parent / "MacReady")
    args = parser.parse_args()
    for library, repo in LIBRARIES.items():
        destination = ROOT / "Vendor" / library
        manifest = destination / "snapshot.json"
        if args.check:
            expected = json.loads(manifest.read_text())["sha256"]
            if expected != files_and_hashes(destination):
                raise SystemExit(f"{library}: snapshot differs; sync from its source repository")
        else:
            source = args.cpsm if repo == "cpsm" else args.macready
            version = (source / "VERSION").read_text().strip()
            source_files = source / "Sources" / library
            if not source_files.is_dir():
                raise SystemExit(f"Missing library: {source_files}")
            destination.mkdir(parents=True, exist_ok=True)
            target = destination / "Sources" / library
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(source_files, target)
            shutil.copy2(source / "LICENSE", destination / "LICENSE")
            (destination / "Package.swift").write_text(f'''// swift-tools-version: 5.9
import PackageDescription

// Generated by scripts/sync-vendor.py from {repo} {version}.
let package = Package(
    name: "{library}",
    platforms: [.macOS("13.5")],
    products: [.library(name: "{library}", targets: ["{library}"])],
    targets: [.target(name: "{library}")],
    swiftLanguageVersions: [.v5]
)
''')
            manifest.write_text(json.dumps({
                "repository": f"https://github.com/fuji-mak/{repo}",
                "version": version,
                "source_directory": f"Sources/{library}",
                "sha256": files_and_hashes(destination)
            }, indent=2, sort_keys=True) + "\n")
        print(f"{library}: {'verified' if args.check else 'synced'}")


if __name__ == "__main__":
    main()
